### ISSUE TITLE
Error initializing cloudprober

### ISSUE THREAD

**Issue by JohnWillker** [google/cloudprober#432]
I followed exactly as it is in [this tutorial](https://cloudprober.org/how-to/run-on-kubernetes/) and had this problem to initialize the pod:

```logs
1 Error initializing cloudprober. Err: Get "http://169.254.169.254/computeMetadata/v1/project/project-id": dial tcp 169.254.169.254:80: connect: connection refused
```

In a locally Kubernetes cluster all the things work perfectly but in the GKE clusters not.

I'm using the last version of Cloudprober and Kubernetes(GKE) in `v1.14.10-gke.36` version

What I'm doing wrong?

Maybe something related to this: https://github.com/google/cloudprober/blob/5c1b57317400f31da67e0a96a009f5e78416f161/cmd/cloudprober.go#L129-L133

**Comment by JohnWillker** [comment]
As I'm using Istio there are these issues:
- https://github.com/istio/istio/issues/13009
- https://github.com/GoogleCloudPlatform/microservices-demo/issues/199
- https://github.com/istio/istio/issues/6593

The solution for while is:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: metadata-google-internal
spec:
  hosts:
    - metadata.google.internal
  http:
    - route:
        - destination:
            host: metadata.google.internal
          headers:
            request:
             remove:
                - x-forwarded-for
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: metadata-google-internal
spec:
  hosts:
    - metadata.google.internal
  addresses:
    - 169.254.169.254
  ports:
    - name: http
      number: 80
      protocol: HTTP
    - name: https
      number: 443
      protocol: HTTPS
  location: MESH_INTERNAL
  resolution: DNS
```

But this solution for some reason add a delay of 20s in the pod startup.
