### ISSUE TITLE
Propose: Kubernetes Deployment

### ISSUE THREAD

**Issue by DazWilkin** [google/cloudprober#89]
Assuming https://github.com/google/cloudprober/issues/88, it's possible to deploy `cloudprober` to Kubernetes and reference a custom config through Kubernetes' `ConfigMap`:

Assuming `cloudconfig.google.cfg`, per the documentation example, this can be uploaded to Kubernetes as a configuration file accessible as `cloudconfig.cfg`:
```bash
kubectl create configmap cloudprober-config \
--from-file=cloudprober.cfg=cloudprober.google.cfg \
--namespace=default
```
or:
```YAML
apiVersion: v1
data:
  cloudprober.cfg: |
    probe {
      name: "google"
      type: HTTP
      targets {
        host_names: "www.google.com"
      }
      interval_msec: 15000  # 15s
      timeout_msec: 1000   # 1s
    }
kind: ConfigMap
metadata:
  name: cloudprober-config
  namespace: default
```
**NB** Rename "cloudprober.cfg" in both as appropriate.

and:
```bash
kubectl describe configmaps/cloudprober-config \
--namespace=default
```
yields:
```
Name:         cloudprober-config
Namespace:    default
Labels:       <none>
Annotations:  <none>

Data
====
cloudprober.cfg:
----
probe {
  name: "google"
  type: HTTP
  targets {
    host_names: "www.google.com"
  }
  interval_msec: 15000  # 15s
  timeout_msec: 1000   # 1s
}
```
Then:
```YAML
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloudprober
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudprober
    spec:
      volumes:
      - name: cloudprober-config
        configMap:
          name: cloudprober-config
      containers:
      - name: cloudprober
        image: cloudprober/cloudprober
        args: [
          "--config_file","/cfg/cloudprober.cfg",
          "--logtostderr"
        ]
        volumeMounts:
        - name: cloudprober-config
          mountPath: /cfg
        ports:
        - name: http
          containerPort: 9313
        env:
        - name: CLOUDPROBER_PORT
          value: "9313"
---
apiVersion: v1
kind: Service
metadata:
  name: cloudprober
  labels:
    app: cloudprober
spec:
  ports:
  - port: 9313
    protocol: TCP
    targetPort: 9313
  selector:
    app: cloudprober
  type: NodePort
```
For some reason, under Kubernetes, `cloudprober` balks if `CLOUDPROBER_PORT` is not set.
